In [1]:
import numpy  as np
import cv2

In [19]:
img=cv2.imread(r'C:\Users\gulsh\OneDrive\Desktop\OPENCV\flower.jpg',1)
pixel=img[150,100]
print(pixel)

    

[186 101  53]


In [11]:
dimensions=img.ndim
height=img.shape[0]
width=img.shape[1]
channels=img.shape[2]
size1=img.size
print('Image Dimension    : ',dimensions)  
print('Image Height       : ',height)  
print('Image Width        : ',width)  
print('Number of Channels : ',channels)  
print('Image Size  :', size1)  

Image Dimension    :  3
Image Height       :  837
Image Width        :  1200
Number of Channels :  3
Image Size  : 3013200


In [13]:
b,g,r=cv2.split(img)
b,g,r

(array([[191, 192, 194, ..., 173, 174, 174],
        [189, 190, 191, ..., 173, 174, 174],
        [188, 189, 190, ..., 173, 174, 174],
        ...,
        [180, 180, 180, ..., 171, 170, 166],
        [180, 180, 180, ..., 170, 170, 167],
        [180, 180, 180, ..., 170, 170, 168]], dtype=uint8),
 array([[104, 105, 107, ...,  86,  87,  87],
        [102, 103, 104, ...,  86,  87,  87],
        [101, 102, 103, ...,  87,  88,  88],
        ...,
        [ 95,  95,  95, ...,  84,  83,  79],
        [ 95,  95,  95, ...,  83,  83,  80],
        [ 95,  95,  95, ...,  83,  83,  81]], dtype=uint8),
 array([[54, 55, 57, ..., 42, 43, 43],
        [52, 53, 54, ..., 42, 43, 43],
        [51, 52, 53, ..., 41, 42, 42],
        ...,
        [47, 47, 47, ..., 40, 39, 35],
        [47, 47, 47, ..., 39, 39, 36],
        [47, 47, 47, ..., 39, 39, 37]], dtype=uint8))

In [15]:
img1=cv2.merge((b,g,r))
img1

array([[[191, 104,  54],
        [192, 105,  55],
        [194, 107,  57],
        ...,
        [173,  86,  42],
        [174,  87,  43],
        [174,  87,  43]],

       [[189, 102,  52],
        [190, 103,  53],
        [191, 104,  54],
        ...,
        [173,  86,  42],
        [174,  87,  43],
        [174,  87,  43]],

       [[188, 101,  51],
        [189, 102,  52],
        [190, 103,  53],
        ...,
        [173,  87,  41],
        [174,  88,  42],
        [174,  88,  42]],

       ...,

       [[180,  95,  47],
        [180,  95,  47],
        [180,  95,  47],
        ...,
        [171,  84,  40],
        [170,  83,  39],
        [166,  79,  35]],

       [[180,  95,  47],
        [180,  95,  47],
        [180,  95,  47],
        ...,
        [170,  83,  39],
        [170,  83,  39],
        [167,  80,  36]],

       [[180,  95,  47],
        [180,  95,  47],
        [180,  95,  47],
        ...,
        [170,  83,  39],
        [170,  83,  39],
        [168,  81,  37]]